export const initialState = {
  categories: [
    { id: 'fire', name: 'Filled with fire', image: 'https://images.gemexi.com/blog-pictures/need-enthusiasm-in-life-access-the-power-of-the-fire-element-learn-how-picture.jpg'},
    { id: 'water', name: 'Filled with water', image: 'https://i0.wp.com/astroligion.com/wp-content/uploads/2019/02/water-element.png?resize=940%2C620&ssl=1'},
    { id: 'air', name: 'Filled with air', image: 'https://i1.wp.com/astroligion.com/wp-content/uploads/2019/02/air-element-1.png?resize=940%2C620&ssl=1'},
    { id: 'earth', name: 'Filled with earth', image: 'https://i.etsystatic.com/15887330/r/il/ba224e/1987449803/il_570xN.1987449803_13vk.jpg'},
    { id: 'amulet', name: 'Amulets', image: 'https://images-na.ssl-images-amazon.com/images/I/91cvLdKoMML._SY500_.jpg'},
  ],
  variants: [
    { id: 'air ring1',
      variant: 'Rosewood',
      image: '' },
    { id: 'air ring1',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'air ring1',
      variant: 'Cherry wood',
      image: '' },
    { id: 'air ring2',
      variant: 'Rosewood',
      image: ''},
    { id: 'air ring2',
      variant: 'Cherry wood',
      image: '' },
    { id: 'air ring2',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'earth ring1',
      variant: 'Rosewood',
      image: '' },
    { id: 'earth ring1',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'earth ring1',
      variant: 'Cherry wood',
      image: '' },
    { id: 'earth ring2',
      variant: 'Rosewood',
      image: '' },
    { id: 'earth ring2',
      variant: 'Mahogany wood',
      image:''},
    { id: 'earth ring2',
      variant: 'Cherry wood',
      image: '' },
    { id: 'fire ring1',
      variant: 'Rosewood',
      image: '' },
    { id: 'fire ring1',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'fire ring1',
      variant: 'Cherry wood',
      image: '' },
    { id: 'fire ring2',
      variant: 'Rosewood',
      image: '' },
    { id: 'fire ring2',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'fire ring2',
      variant: 'Cherry wood',
      image: '' },
    { id: 'fire ring3',
      variant: 'Rosewood',
      image: '' },
    { id: 'fire ring3',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'fire ring3',
      variant: 'Cherry wood',
      image: '' },
    { id: 'water ring1',
      variant: 'Rosewood',
      image: '' },
    { id: 'water ring1',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'water ring1',
      variant: 'Cherry wood',
      image: '' },
    { id: 'water ring2',
      variant: 'Rosewood',
      image: '' },
    { id: 'water ring2',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'water ring2',
      variant: 'Cherry wood',
      image: '' },
    { id: 'water ring3',
      variant: 'Rosewood',
      image: '' },
    { id: 'water ring3',
      variant: 'Mahogany wood',
      image: '' },
    { id: 'water ring3',
      variant: 'Cherry wood',
      image: '' },
  ],

  rings: {
    data: [
      {
        _id: '1',
        name: 'earth ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/25/glass-and-wood-ring-2636613_960_720.jpg',
        variant: 'earth ring1',
        description: 'Test desc1',
        price: 50,
        rate: 4,
        category: 'earth',
        productSelect: 'Select wood material',
      },
      {
        _id: '2',
        name: 'fire ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/23/glass-and-wood-ring-2636608_960_720.jpg',
        variant: 'fire ring1',
        description: 'Test desc1',
        price: 250,
        rate: 3,
        category: 'fire',
        productSelect: 'Select wood material',
      },
      {
        _id: '3',
        name: 'water ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/13/glass-and-wood-ring-2636592_960_720.jpg',
        variant: 'water ring1',
        description: 'Test desc1',
        price: 50,
        rate: 5,
        category: 'water',
        productSelect: 'Select wood material',
      },
      {
        _id: '4',
        name: 'air ring',
        image: 'https://cdn.thisiswhyimbroke.com/images/handmade-wooden-rings-640x534.jpg',
        variant: 'air ring1',
        description: 'Test desc1',
        price: 55,
        rate: 2,
        category: 'Air',
        productSelect: 'Select wood material',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  cart: {
    rings: [],
  },
};
