export const initialState = {
  categories: [
    { id: 'fire', name: 'Filled with fire', image: 'https://static.wikia.nocookie.net/great-demon-king-en/images/4/44/Fire-element.png/revision/latest?cb=20200408120517'},
    { id: 'water', name: 'Filled with water', image: 'https://i0.wp.com/astroligion.com/wp-content/uploads/2019/02/water-element.png?resize=940%2C620&ssl=1'},
    { id: 'air', name: 'Filled with air', image: 'https://i1.wp.com/astroligion.com/wp-content/uploads/2019/02/air-element-1.png?resize=940%2C620&ssl=1'},
    { id: 'earth', name: 'Filled with earth', image: 'https://i.etsystatic.com/15887330/r/il/ba224e/1987449803/il_570xN.1987449803_13vk.jpg'},
  ],
  options: [
    { id: 'air ring1',
      option: 'Rosewood',
      image: '' },
    { id: 'air ring1',
      option: 'Mahogany wood',
      image: '' },
    { id: 'air ring1',
      option: 'Cherry wood',
      image: '' },
    { id: 'air ring2',
      option: 'Rosewood',
      image: ''},
    { id: 'air ring2',
      option: 'Cherry wood',
      image: '' },
    { id: 'air ring2',
      option: 'Mahogany wood',
      image: '' },
    { id: 'earth ring1',
      option: 'Rosewood',
      image: '' },
    { id: 'earth ring1',
      option: 'Mahogany wood',
      image: '' },
    { id: 'earth ring1',
      option: 'Cherry wood',
      image: '' },
    { id: 'earth ring2',
      option: 'Rosewood',
      image: '' },
    { id: 'earth ring2',
      option: 'Mahogany wood',
      image:''},
    { id: 'earth ring2',
      option: 'Cherry wood',
      image: '' },
    { id: 'fire ring1',
      option: 'Rosewood',
      image: '' },
    { id: 'fire ring1',
      option: 'Mahogany wood',
      image: '' },
    { id: 'fire ring1',
      option: 'Cherry wood',
      image: '' },
    { id: 'fire ring2',
      option: 'Rosewood',
      image: '' },
    { id: 'fire ring2',
      option: 'Mahogany wood',
      image: '' },
    { id: 'fire ring2',
      option: 'Cherry wood',
      image: '' },
    { id: 'fire ring3',
      option: 'Rosewood',
      image: '' },
    { id: 'fire ring3',
      option: 'Mahogany wood',
      image: '' },
    { id: 'fire ring3',
      option: 'Cherry wood',
      image: '' },
    { id: 'water ring1',
      option: 'Rosewood',
      image: '' },
    { id: 'water ring1',
      option: 'Mahogany wood',
      image: '' },
    { id: 'water ring1',
      option: 'Cherry wood',
      image: '' },
    { id: 'water ring2',
      option: 'Rosewood',
      image: '' },
    { id: 'water ring2',
      option: 'Mahogany wood',
      image: '' },
    { id: 'water ring2',
      option: 'Cherry wood',
      image: '' },
    { id: 'water ring3',
      option: 'Rosewood',
      image: '' },
    { id: 'water ring3',
      option: 'Mahogany wood',
      image: '' },
    { id: 'water ring3',
      option: 'Cherry wood',
      image: '' },
  ],

  rings: {
    data: [
      {
        _id: '1',
        name: 'earth ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/25/glass-and-wood-ring-2636613_960_720.jpg',
        option: 'earth ring1',
        description: 'Test desc1',
        price: 50,
        rate: 4,
        cathegory: 'earth',
        productSelect: 'Select wood material',
      },
      {
        _id: '2',
        name: 'fire ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/23/glass-and-wood-ring-2636608_960_720.jpg',
        option: 'fire ring1',
        description: 'Test desc1',
        price: 250,
        rate: 3,
        cathegory: 'fire',
        productSelect: 'Select wood material',
      },
      {
        _id: '3',
        name: 'water ring',
        image: 'https://cdn.pixabay.com/photo/2017/08/13/09/13/glass-and-wood-ring-2636592_960_720.jpg',
        option: 'water ring1',
        description: 'Test desc1',
        price: 50,
        rate: 5,
        cathegory: 'water',
        productSelect: 'Select wood material',
      },
      {
        _id: '4',
        name: 'air ring',
        image: 'https://cdn.thisiswhyimbroke.com/images/handmade-wooden-rings-640x534.jpg',
        option: 'air ring1',
        description: 'Test desc1',
        price: 55,
        rate: 2,
        cathegory: 'Air',
        productSelect: 'Select wood material',
      },
    ],
    loading: {
      active: false,
      error: false,
    },
  },
  cart: {
    rings: [],
  },
};
